# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ovKZu0otwUew3oOJrP64HNMN3da-AR8
"""

import sys
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import io
import csv

# --- Configuración visual de la página ---
st.set_page_config(page_title="Análisis Académico", page_icon="📊", layout="wide")

# --- Funciones de procesamiento ---
@st.cache_data # Mantiene los datos en memoria para no recargar en cada clic
def procesar_archivos(archivos_subidos):
    all_dfs = []
    for archivo in archivos_subidos:
        try:
            content = archivo.getvalue().decode('utf-8-sig')
            file_stream = io.StringIO(content)

            # Intentar detectar el delimitador
            delimiter = ','
            try:
                sample = file_stream.readline()
                sniffer = csv.Sniffer()
                dialect = sniffer.sniff(sample, delimiters=';,\t')
                delimiter = dialect.delimiter
                file_stream.seek(0)
            except csv.Error:
                file_stream.seek(0)
                if ';' in content: delimiter = ';'
                elif '\t' in content: delimiter = '\t'

            df = pd.read_csv(file_stream, delimiter=delimiter)

            if 'Nombre' not in df.columns:
                st.error(f"Error en '{archivo.name}': La columna 'Nombre' no se encontró.")
                continue

            grade_columns = [col for col in df.columns if col != 'Nombre']
            for col in grade_columns:
                df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0.0)

            all_dfs.append(df)
        except Exception as e:
            st.error(f"Error al procesar '{archivo.name}': {e}")

    if all_dfs:
        return pd.concat(all_dfs, ignore_index=True)
    return pd.DataFrame()

# --- Interfaz de Usuario (UI) ---
st.title("📊 Sistema de Análisis Académico")
st.markdown("Sube tus archivos de calificaciones para visualizar el rendimiento del curso de forma interactiva.")

# 1. Zona de carga de archivos
archivos = st.file_uploader("Sube tus archivos de calificaciones (CSV o TXT)", type=['csv', 'txt'], accept_multiple_files=True)

if archivos:
    df_estudiantes = procesar_archivos(archivos)

    if not df_estudiantes.empty:
        st.success("✅ Archivos cargados y consolidados exitosamente.")

        # Mostrar los datos brutos opcionalmente
        with st.expander("Ver tabla de datos consolidados"):
            st.dataframe(df_estudiantes, use_container_width=True)

        # Crear pestañas para las diferentes funcionalidades
        tab1, tab2, tab3 = st.tabs(["🏆 Mejor/Peor Rendimiento", "🔍 Buscar Estudiante", "📈 Gráficos de Rendimiento"])

        grade_columns = [col for col in df_estudiantes.columns if col != 'Nombre']

        # --- Pestaña 1: Mejor y Peor ---
        with tab1:
            st.header("Rendimiento Destacado")
            df_temp = df_estudiantes.copy()
            df_temp['Promedio'] = df_temp[grade_columns].mean(axis=1)

            mejor = df_temp.loc[df_temp['Promedio'].idxmax()]
            peor = df_temp.loc[df_temp['Promedio'].idxmin()]

            col1, col2 = st.columns(2)
            with col1:
                st.metric(label="🌟 Mejor Estudiante", value=mejor['Nombre'], delta=f"Promedio: {mejor['Promedio']:.2f}")
            with col2:
                st.metric(label="⚠️ Estudiante con menor promedio", value=peor['Nombre'], delta=f"Promedio: {peor['Promedio']:.2f}", delta_color="inverse")

        # --- Pestaña 2: Buscador ---
        with tab2:
            st.header("Buscar Estudiante")
            busqueda = st.text_input("Introduce el nombre del estudiante a buscar (Debes buscar el nombre exactamente como aparece en el archivo que cargaste):")

            if busqueda:
                encontrados = df_estudiantes[df_estudiantes['Nombre'].str.lower().str.contains(busqueda.lower(), na=False)]

                if not encontrados.empty:
                    for index, estudiante in encontrados.iterrows():
                        st.subheader(f"Calificaciones de {estudiante['Nombre']}")
                        promedio = estudiante[grade_columns].mean()
                        st.info(f"**PROMEDIO GLOBAL:** {promedio:.2f}")

                        # Mostramos las notas en formato de tabla limpia
                        df_notas = pd.DataFrame([estudiante[grade_columns]])
                        st.dataframe(df_notas, use_container_width=True)
                else:
                    st.warning("No se encontró ningún estudiante con ese nombre.")

        # --- Pestaña 3: Gráficos ---
        with tab3:
            st.header("Análisis Gráfico")

            tipo_grafico = st.radio(
                "Selecciona qué deseas visualizar:",
                [
                    "Promedio General del Curso",
                    "Rendimiento de un Estudiante Específico",
                    "Comparativa de Todos los Estudiantes (Promedios)"
                ]
            )

            if tipo_grafico == "Promedio General del Curso":
                data_to_plot = df_estudiantes[grade_columns].mean()
                titulo = 'Promedio General del Curso por Asignatura'

                st.subheader(titulo)
                st.bar_chart(data_to_plot, color="#2196F3")

            elif tipo_grafico == "Rendimiento de un Estudiante Específico":
                lista_nombres = df_estudiantes['Nombre'].tolist()
                estudiante_seleccionado = st.selectbox("Selecciona un estudiante:", lista_nombres)

                student_data = df_estudiantes[df_estudiantes['Nombre'] == estudiante_seleccionado].iloc[0]
                data_to_plot = student_data[grade_columns]
                titulo = f'Rendimiento de {estudiante_seleccionado} por Asignatura'

                st.subheader(titulo)
                st.bar_chart(data_to_plot, color="#4CAF50")

            # SECCIÓN MODIFICADA: Ahora despliega un gráfico de líneas
            elif tipo_grafico == "Comparativa de Todos los Estudiantes (Promedios)":
                st.subheader("Promedio General por Estudiante")
                st.markdown("Visualiza el rendimiento de todo el grupo ordenado de **mayor a menor**.")

                # Clonamos para calcular promedios sin alterar el original
                df_comparativa = df_estudiantes.copy()
                df_comparativa

